//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameInputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputController"",
    ""maps"": [
        {
            ""name"": ""SpawnCube"",
            ""id"": ""37419e56-5eec-41bb-957d-5502565a968d"",
            ""actions"": [
                {
                    ""name"": ""Keyboard"",
                    ""type"": ""Button"",
                    ""id"": ""0cf3c40d-d698-48c6-a0bd-aa14687e0062"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e9f79132-ac73-45fb-abb4-e998e740f375"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SpawnCube
        m_SpawnCube = asset.FindActionMap("SpawnCube", throwIfNotFound: true);
        m_SpawnCube_Keyboard = m_SpawnCube.FindAction("Keyboard", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SpawnCube
    private readonly InputActionMap m_SpawnCube;
    private List<ISpawnCubeActions> m_SpawnCubeActionsCallbackInterfaces = new List<ISpawnCubeActions>();
    private readonly InputAction m_SpawnCube_Keyboard;
    public struct SpawnCubeActions
    {
        private @GameInputController m_Wrapper;
        public SpawnCubeActions(@GameInputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Keyboard => m_Wrapper.m_SpawnCube_Keyboard;
        public InputActionMap Get() { return m_Wrapper.m_SpawnCube; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SpawnCubeActions set) { return set.Get(); }
        public void AddCallbacks(ISpawnCubeActions instance)
        {
            if (instance == null || m_Wrapper.m_SpawnCubeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SpawnCubeActionsCallbackInterfaces.Add(instance);
            @Keyboard.started += instance.OnKeyboard;
            @Keyboard.performed += instance.OnKeyboard;
            @Keyboard.canceled += instance.OnKeyboard;
        }

        private void UnregisterCallbacks(ISpawnCubeActions instance)
        {
            @Keyboard.started -= instance.OnKeyboard;
            @Keyboard.performed -= instance.OnKeyboard;
            @Keyboard.canceled -= instance.OnKeyboard;
        }

        public void RemoveCallbacks(ISpawnCubeActions instance)
        {
            if (m_Wrapper.m_SpawnCubeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISpawnCubeActions instance)
        {
            foreach (var item in m_Wrapper.m_SpawnCubeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SpawnCubeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SpawnCubeActions @SpawnCube => new SpawnCubeActions(this);
    public interface ISpawnCubeActions
    {
        void OnKeyboard(InputAction.CallbackContext context);
    }
}
